#!/usr/bin/env python3
"""
data_check.py

Check one FR5 multimodal episode folder generated by the recorder.

Example:
    python3 data_check.py /home/xjtlu/xbox_control/fr5_dp_data/episode_000001

Optional:
    python3 data_check.py /home/xjtlu/xbox_control/fr5_dp_data/episode_000001 --save-vis
"""

import argparse
import json
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np


REQUIRED_FILES = [
    "timestamps.npy",
    "joint_pos.npy",
    "eef_pose.npy",
    "gripper_state.npy",
    "rgb_frames.npy",
    "env_rgb_frames.npy",
    "depth_frames.npy",
    "env_depth_frames.npy",
    "action_delta.npy",
    "rgb_timestamps.npy",
    "env_rgb_timestamps.npy",
    "depth_timestamps.npy",
    "env_depth_timestamps.npy",
]

OPTIONAL_FILES = [
    "pointcloud_frames.npy",
    "pointcloud_timestamps.npy",
    "meta.json",
]


def load_npy(path: Path, mmap: bool = False) -> np.ndarray:
    if mmap:
        return np.load(path, mmap_mode="r", allow_pickle=False)
    return np.load(path, allow_pickle=False)


def arr_basic_stats(name: str, arr: np.ndarray) -> str:
    line = f"{name:<24} shape={str(arr.shape):<22} dtype={str(arr.dtype):<10}"
    if arr.size == 0:
        return line + " EMPTY"

    flat = arr.reshape(-1)
    if flat.size > 2_000_000:
        idx = np.linspace(0, flat.size - 1, 2_000_000).astype(np.int64)
        flat = flat[idx]

    if np.issubdtype(arr.dtype, np.number):
        finite = np.isfinite(flat)
        finite_ratio = float(finite.mean()) if finite.size > 0 else 0.0
        if finite.any():
            vals = flat[finite]
            line += (
                f" min={float(vals.min()):.5g}"
                f" max={float(vals.max()):.5g}"
                f" mean={float(vals.mean()):.5g}"
                f" finite={finite_ratio:.4f}"
            )
        else:
            line += f" finite={finite_ratio:.4f}"
    return line


def check_exists(ep_dir: Path) -> Tuple[bool, Dict[str, Path]]:
    print("\n========== File existence ==========")
    file_map = {}
    ok = True

    for fname in REQUIRED_FILES:
        path = ep_dir / fname
        file_map[fname] = path
        if path.exists():
            print(f"[OK]       {fname}")
        else:
            print(f"[MISSING]  {fname}")
            ok = False

    for fname in OPTIONAL_FILES:
        path = ep_dir / fname
        file_map[fname] = path
        if path.exists():
            print(f"[OPTIONAL] {fname}")
        else:
            print(f"[SKIP]     {fname}")

    return ok, file_map


def check_meta(ep_dir: Path):
    meta_path = ep_dir / "meta.json"
    print("\n========== meta.json ==========")
    if not meta_path.exists():
        print("[WARN] meta.json not found.")
        return

    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        print(json.dumps(meta, indent=2, ensure_ascii=False))
    except Exception as e:
        print(f"[ERROR] Failed to read meta.json: {e}")


def check_shapes(data: Dict[str, np.ndarray]) -> bool:
    print("\n========== Shape alignment ==========")

    ok = True
    T_ref = None

    for name, arr in data.items():
        if not name.endswith(".npy"):
            continue
        if arr.ndim == 0:
            print(f"[WARN] {name} is scalar.")
            continue

        T = arr.shape[0]
        if T_ref is None:
            T_ref = T
            print(f"[REF]  T = {T_ref} from {name}")
        elif T != T_ref:
            print(f"[BAD]  {name}: T={T}, expected T={T_ref}")
            ok = False
        else:
            print(f"[OK]   {name}: T={T}")

    if "action_delta.npy" in data:
        action = data["action_delta.npy"]
        if action.ndim != 2 or action.shape[1] != 7:
            print(f"[BAD]  action_delta.npy shape should be [T, 7], got {action.shape}")
            ok = False
        else:
            print("[OK]   action_delta.npy shape is [T, 7]")

    expected_shapes = {
        "joint_pos.npy": (2, 6),
        "eef_pose.npy": (2, 6),
        "gripper_state.npy": (2, 1),
    }
    for fname, (ndim, second_dim) in expected_shapes.items():
        if fname in data:
            arr = data[fname]
            if arr.ndim != ndim or arr.shape[1] != second_dim:
                print(f"[BAD]  {fname} shape should be [T, {second_dim}], got {arr.shape}")
                ok = False

    return ok


def check_timestamps(data: Dict[str, np.ndarray]):
    print("\n========== Timestamp checks ==========")

    if "timestamps.npy" in data:
        ts = data["timestamps.npy"]
        print(arr_basic_stats("timestamps.npy", ts))
        if ts.ndim == 1 and len(ts) >= 2:
            dt = np.diff(ts)
            print(
                f"main dt: min={dt.min():.5f}s max={dt.max():.5f}s "
                f"mean={dt.mean():.5f}s std={dt.std():.5f}s approx_hz={1.0 / dt.mean():.2f}"
            )
            if np.any(dt <= 0):
                print("[BAD] timestamps are not strictly increasing.")
            else:
                print("[OK] timestamps are strictly increasing.")

    if "timestamps.npy" not in data:
        return

    sample_ts = data["timestamps.npy"]
    pairs = [
        ("rgb_timestamps.npy", "RGB"),
        ("env_rgb_timestamps.npy", "Env RGB"),
        ("depth_timestamps.npy", "Depth"),
        ("env_depth_timestamps.npy", "Env Depth"),
        ("pointcloud_timestamps.npy", "PointCloud"),
    ]

    for fname, label in pairs:
        if fname not in data:
            continue
        sensor_ts = data[fname]
        if sensor_ts.shape[0] != sample_ts.shape[0]:
            print(f"[WARN] {label}: timestamp length mismatch {sensor_ts.shape[0]} vs {sample_ts.shape[0]}")
            continue
        valid = sensor_ts > 0
        if valid.any():
            lag = sample_ts[valid] - sensor_ts[valid]
            print(
                f"{label:<10} cache lag: "
                f"min={lag.min():.5f}s max={lag.max():.5f}s "
                f"mean={lag.mean():.5f}s std={lag.std():.5f}s valid={valid.mean():.3f}"
            )
        else:
            print(f"[WARN] {label}: all sensor timestamps are 0.")


def check_depth(name: str, depth: np.ndarray):
    print(f"\n========== Depth quality: {name} ==========")
    print(arr_basic_stats(name, depth))

    if depth.ndim != 3:
        print(f"[WARN] {name} expected shape [T, H, W], got {depth.shape}")
        return

    zero_ratio_per_frame = []
    valid_ratio_per_frame = []
    positive_depth_per_frame = []

    for i in range(depth.shape[0]):
        d = depth[i]
        finite = np.isfinite(d)
        valid = finite & (d > 0)
        zero_ratio_per_frame.append(float((d == 0).mean()))
        valid_ratio_per_frame.append(float(valid.mean()))
        if valid.any():
            positive_depth_per_frame.append(float(d[valid].mean()))
        else:
            positive_depth_per_frame.append(0.0)

    zero_ratio_per_frame = np.array(zero_ratio_per_frame)
    valid_ratio_per_frame = np.array(valid_ratio_per_frame)
    positive_depth_per_frame = np.array(positive_depth_per_frame)

    print(
        f"zero_ratio:  min={zero_ratio_per_frame.min():.4f} "
        f"max={zero_ratio_per_frame.max():.4f} "
        f"mean={zero_ratio_per_frame.mean():.4f}"
    )
    print(
        f"valid_ratio: min={valid_ratio_per_frame.min():.4f} "
        f"max={valid_ratio_per_frame.max():.4f} "
        f"mean={valid_ratio_per_frame.mean():.4f}"
    )
    print(
        f"positive depth mean per frame: min={positive_depth_per_frame.min():.4f}m "
        f"max={positive_depth_per_frame.max():.4f}m "
        f"mean={positive_depth_per_frame.mean():.4f}m"
    )

    if valid_ratio_per_frame.mean() < 0.1:
        print("[WARN] valid depth ratio is very low. Check depth topic, unit, or camera view.")
    elif valid_ratio_per_frame.mean() < 0.5:
        print("[WARN] many depth pixels are invalid/zero.")
    else:
        print("[OK] depth has a reasonable amount of valid pixels.")


def check_rgb(name: str, rgb: np.ndarray):
    print(f"\n========== RGB quality: {name} ==========")
    print(arr_basic_stats(name, rgb))

    if rgb.ndim != 4 or rgb.shape[-1] != 3:
        print(f"[WARN] {name} expected shape [T, H, W, 3], got {rgb.shape}")
        return

    if rgb.shape[0] >= 2:
        diffs = []
        for i in range(1, min(rgb.shape[0], 50)):
            diff = np.mean(np.abs(rgb[i].astype(np.float32) - rgb[i - 1].astype(np.float32)))
            diffs.append(diff)
        diffs = np.array(diffs)
        print(
            f"adjacent frame abs diff sample: min={diffs.min():.4f} "
            f"max={diffs.max():.4f} mean={diffs.mean():.4f}"
        )
        if diffs.mean() < 0.1:
            print("[WARN] RGB frames barely change. This is okay if robot/camera is static, otherwise check subscription.")
        else:
            print("[OK] RGB frames have visible variation in sampled diffs.")


def check_action_motion(data: Dict[str, np.ndarray]):
    print("\n========== Action / motion checks ==========")

    if "action_delta.npy" in data:
        action = data["action_delta.npy"]
        print(arr_basic_stats("action_delta.npy", action))
        if action.ndim == 2 and action.shape[1] == 7:
            trans_norm = np.linalg.norm(action[:, :3], axis=1)
            rot_norm = np.linalg.norm(action[:, 3:6], axis=1)
            grip_abs = np.abs(action[:, 6])
            print(
                f"translation delta norm: min={trans_norm.min():.6f} "
                f"max={trans_norm.max():.6f} mean={trans_norm.mean():.6f}"
            )
            print(
                f"rotation delta norm:    min={rot_norm.min():.6f} "
                f"max={rot_norm.max():.6f} mean={rot_norm.mean():.6f}"
            )
            print(
                f"gripper delta abs:      min={grip_abs.min():.6f} "
                f"max={grip_abs.max():.6f} mean={grip_abs.mean():.6f}"
            )

            if np.allclose(action, 0):
                print("[BAD] action_delta is all zeros.")
            elif trans_norm.mean() < 1e-6 and rot_norm.mean() < 1e-6 and grip_abs.mean() < 1e-6:
                print("[WARN] action deltas are extremely small.")
            else:
                print("[OK] action_delta contains non-zero motion.")

    if "eef_pose.npy" in data:
        print(arr_basic_stats("eef_pose.npy", data["eef_pose.npy"]))


def save_visualizations(ep_dir: Path, data: Dict[str, np.ndarray], out_dir: Optional[Path] = None):
    import matplotlib.pyplot as plt

    if out_dir is None:
        out_dir = ep_dir / "check_vis"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n========== Saving visualizations to {out_dir} ==========")

    def save_rgb_grid(fname: str, title: str):
        if fname not in data:
            return
        arr = data[fname]
        if arr.ndim != 4 or arr.shape[-1] != 3 or arr.shape[0] == 0:
            return

        idxs = np.linspace(0, arr.shape[0] - 1, min(4, arr.shape[0])).astype(int)
        fig, axes = plt.subplots(1, len(idxs), figsize=(4 * len(idxs), 4))
        if len(idxs) == 1:
            axes = [axes]
        for ax, idx in zip(axes, idxs):
            img = arr[idx][..., ::-1]  # BGR -> RGB
            ax.imshow(img)
            ax.set_title(f"{title} t={idx}")
            ax.axis("off")
        fig.tight_layout()
        fig.savefig(out_dir / f"{fname.replace('.npy', '')}_preview.png", dpi=150)
        plt.close(fig)

    def save_depth_grid(fname: str, title: str):
        if fname not in data:
            return
        arr = data[fname]
        if arr.ndim != 3 or arr.shape[0] == 0:
            return

        idxs = np.linspace(0, arr.shape[0] - 1, min(4, arr.shape[0])).astype(int)
        fig, axes = plt.subplots(1, len(idxs), figsize=(4 * len(idxs), 4))
        if len(idxs) == 1:
            axes = [axes]
        for ax, idx in zip(axes, idxs):
            d = arr[idx]
            valid = d[d > 0]
            if valid.size > 0:
                vmax = np.percentile(valid, 95)
                vmin = np.percentile(valid, 5)
            else:
                vmin, vmax = 0.0, 1.0
            im = ax.imshow(d, cmap="viridis", vmin=vmin, vmax=vmax)
            ax.set_title(f"{title} t={idx}")
            ax.axis("off")
            fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        fig.tight_layout()
        fig.savefig(out_dir / f"{fname.replace('.npy', '')}_preview.png", dpi=150)
        plt.close(fig)

    save_rgb_grid("rgb_frames.npy", "RGB")
    save_rgb_grid("env_rgb_frames.npy", "Env RGB")
    save_depth_grid("depth_frames.npy", "Depth")
    save_depth_grid("env_depth_frames.npy", "Env Depth")

    if "action_delta.npy" in data:
        action = data["action_delta.npy"]
        if action.ndim == 2 and action.shape[1] == 7:
            fig = plt.figure(figsize=(12, 5))
            for i, label in enumerate(["dx", "dy", "dz", "droll", "dpitch", "dyaw", "dgripper"]):
                plt.plot(action[:, i], label=label)
            plt.title("action_delta")
            plt.xlabel("t")
            plt.legend()
            plt.tight_layout()
            fig.savefig(out_dir / "action_delta_plot.png", dpi=150)
            plt.close(fig)

    print("[OK] visualizations saved.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("episode_dir", type=str, help="Path to episode_xxxxxx directory")
    parser.add_argument("--save-vis", action="store_true", help="Save preview images and action plot")
    parser.add_argument("--mmap", action="store_true", help="Use numpy mmap_mode='r' for lower memory usage")
    args = parser.parse_args()

    ep_dir = Path(args.episode_dir).expanduser().resolve()
    if not ep_dir.exists():
        raise FileNotFoundError(f"Episode directory does not exist: {ep_dir}")

    print(f"Checking episode: {ep_dir}")

    exists_ok, _ = check_exists(ep_dir)
    check_meta(ep_dir)

    print("\n========== Loading arrays ==========")
    data: Dict[str, np.ndarray] = {}

    for fname in REQUIRED_FILES + OPTIONAL_FILES:
        path = ep_dir / fname
        if not path.exists() or not fname.endswith(".npy"):
            continue
        try:
            arr = load_npy(path, mmap=args.mmap)
            data[fname] = arr
            print(arr_basic_stats(fname, arr))
        except Exception as e:
            print(f"[ERROR] failed to load {fname}: {e}")

    if not exists_ok:
        print("\n[WARN] Some required files are missing. Checks will continue with available files.")

    shape_ok = check_shapes(data)
    check_timestamps(data)

    if "rgb_frames.npy" in data:
        check_rgb("rgb_frames.npy", data["rgb_frames.npy"])
    if "env_rgb_frames.npy" in data:
        check_rgb("env_rgb_frames.npy", data["env_rgb_frames.npy"])

    if "depth_frames.npy" in data:
        check_depth("depth_frames.npy", data["depth_frames.npy"])
    if "env_depth_frames.npy" in data:
        check_depth("env_depth_frames.npy", data["env_depth_frames.npy"])

    if "pointcloud_frames.npy" in data:
        print("\n========== Point cloud checks ==========")
        pc = data["pointcloud_frames.npy"]
        print(arr_basic_stats("pointcloud_frames.npy", pc))
        if pc.ndim == 3 and pc.shape[-1] == 3:
            finite = np.isfinite(pc).all(axis=-1)
            nonzero = np.linalg.norm(pc, axis=-1) > 0
            valid = finite & nonzero
            print(f"point valid ratio: mean={valid.mean():.4f}")
            print("[OK] pointcloud shape looks like [T, N, 3].")
        else:
            print(f"[WARN] expected pointcloud shape [T, N, 3], got {pc.shape}")

    check_action_motion(data)

    if args.save_vis:
        save_visualizations(ep_dir, data)

    print("\n========== Final summary ==========")
    if shape_ok and exists_ok:
        print("[PASS] Basic dataset structure looks good.")
    else:
        print("[CHECK] Some issues were found above. Please inspect warnings/errors.")


if __name__ == "__main__":
    main()
#!/usr/bin/env python3
"""
data_check.py

Check one FR5 multimodal episode folder generated by the recorder.

Example:
    python3 data_check.py /home/xjtlu/xbox_control/fr5_dp_data/episode_000001

Optional:
    python3 data_check.py /home/xjtlu/xbox_control/fr5_dp_data/episode_000001 --save-vis
"""

import argparse
import json
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np


REQUIRED_FILES = [
    "timestamps.npy",
    "joint_pos.npy",
    "eef_pose.npy",
    "gripper_state.npy",
    "rgb_frames.npy",
    "env_rgb_frames.npy",
    "depth_frames.npy",
    "env_depth_frames.npy",
    "action_delta.npy",
    "rgb_timestamps.npy",
    "env_rgb_timestamps.npy",
    "depth_timestamps.npy",
    "env_depth_timestamps.npy",
]

OPTIONAL_FILES = [
    "pointcloud_frames.npy",
    "pointcloud_timestamps.npy",
    "meta.json",
]


def load_npy(path: Path, mmap: bool = False) -> np.ndarray:
    if mmap:
        return np.load(path, mmap_mode="r", allow_pickle=False)
    return np.load(path, allow_pickle=False)


def arr_basic_stats(name: str, arr: np.ndarray) -> str:
    line = f"{name:<24} shape={str(arr.shape):<22} dtype={str(arr.dtype):<10}"
    if arr.size == 0:
        return line + " EMPTY"

    flat = arr.reshape(-1)
    if flat.size > 2_000_000:
        idx = np.linspace(0, flat.size - 1, 2_000_000).astype(np.int64)
        flat = flat[idx]

    if np.issubdtype(arr.dtype, np.number):
        finite = np.isfinite(flat)
        finite_ratio = float(finite.mean()) if finite.size > 0 else 0.0
        if finite.any():
            vals = flat[finite]
            line += (
                f" min={float(vals.min()):.5g}"
                f" max={float(vals.max()):.5g}"
                f" mean={float(vals.mean()):.5g}"
                f" finite={finite_ratio:.4f}"
            )
        else:
            line += f" finite={finite_ratio:.4f}"
    return line


def check_exists(ep_dir: Path) -> Tuple[bool, Dict[str, Path]]:
    print("\n========== File existence ==========")
    file_map = {}
    ok = True

    for fname in REQUIRED_FILES:
        path = ep_dir / fname
        file_map[fname] = path
        if path.exists():
            print(f"[OK]       {fname}")
        else:
            print(f"[MISSING]  {fname}")
            ok = False

    for fname in OPTIONAL_FILES:
        path = ep_dir / fname
        file_map[fname] = path
        if path.exists():
            print(f"[OPTIONAL] {fname}")
        else:
            print(f"[SKIP]     {fname}")

    return ok, file_map


def check_meta(ep_dir: Path):
    meta_path = ep_dir / "meta.json"
    print("\n========== meta.json ==========")
    if not meta_path.exists():
        print("[WARN] meta.json not found.")
        return

    try:
        meta = json.loads(meta_path.read_text(encoding="utf-8"))
        print(json.dumps(meta, indent=2, ensure_ascii=False))
    except Exception as e:
        print(f"[ERROR] Failed to read meta.json: {e}")


def check_shapes(data: Dict[str, np.ndarray]) -> bool:
    print("\n========== Shape alignment ==========")

    ok = True
    T_ref = None

    for name, arr in data.items():
        if not name.endswith(".npy"):
            continue
        if arr.ndim == 0:
            print(f"[WARN] {name} is scalar.")
            continue

        T = arr.shape[0]
        if T_ref is None:
            T_ref = T
            print(f"[REF]  T = {T_ref} from {name}")
        elif T != T_ref:
            print(f"[BAD]  {name}: T={T}, expected T={T_ref}")
            ok = False
        else:
            print(f"[OK]   {name}: T={T}")

    if "action_delta.npy" in data:
        action = data["action_delta.npy"]
        if action.ndim != 2 or action.shape[1] != 7:
            print(f"[BAD]  action_delta.npy shape should be [T, 7], got {action.shape}")
            ok = False
        else:
            print("[OK]   action_delta.npy shape is [T, 7]")

    expected_shapes = {
        "joint_pos.npy": (2, 6),
        "eef_pose.npy": (2, 6),
        "gripper_state.npy": (2, 1),
    }
    for fname, (ndim, second_dim) in expected_shapes.items():
        if fname in data:
            arr = data[fname]
            if arr.ndim != ndim or arr.shape[1] != second_dim:
                print(f"[BAD]  {fname} shape should be [T, {second_dim}], got {arr.shape}")
                ok = False

    return ok


def check_timestamps(data: Dict[str, np.ndarray]):
    print("\n========== Timestamp checks ==========")

    if "timestamps.npy" in data:
        ts = data["timestamps.npy"]
        print(arr_basic_stats("timestamps.npy", ts))
        if ts.ndim == 1 and len(ts) >= 2:
            dt = np.diff(ts)
            print(
                f"main dt: min={dt.min():.5f}s max={dt.max():.5f}s "
                f"mean={dt.mean():.5f}s std={dt.std():.5f}s approx_hz={1.0 / dt.mean():.2f}"
            )
            if np.any(dt <= 0):
                print("[BAD] timestamps are not strictly increasing.")
            else:
                print("[OK] timestamps are strictly increasing.")

    if "timestamps.npy" not in data:
        return

    sample_ts = data["timestamps.npy"]
    pairs = [
        ("rgb_timestamps.npy", "RGB"),
        ("env_rgb_timestamps.npy", "Env RGB"),
        ("depth_timestamps.npy", "Depth"),
        ("env_depth_timestamps.npy", "Env Depth"),
        ("pointcloud_timestamps.npy", "PointCloud"),
    ]

    for fname, label in pairs:
        if fname not in data:
            continue
        sensor_ts = data[fname]
        if sensor_ts.shape[0] != sample_ts.shape[0]:
            print(f"[WARN] {label}: timestamp length mismatch {sensor_ts.shape[0]} vs {sample_ts.shape[0]}")
            continue
        valid = sensor_ts > 0
        if valid.any():
            lag = sample_ts[valid] - sensor_ts[valid]
            print(
                f"{label:<10} cache lag: "
                f"min={lag.min():.5f}s max={lag.max():.5f}s "
                f"mean={lag.mean():.5f}s std={lag.std():.5f}s valid={valid.mean():.3f}"
            )
        else:
            print(f"[WARN] {label}: all sensor timestamps are 0.")


def check_depth(name: str, depth: np.ndarray):
    print(f"\n========== Depth quality: {name} ==========")
    print(arr_basic_stats(name, depth))

    if depth.ndim != 3:
        print(f"[WARN] {name} expected shape [T, H, W], got {depth.shape}")
        return

    zero_ratio_per_frame = []
    valid_ratio_per_frame = []
    positive_depth_per_frame = []

    for i in range(depth.shape[0]):
        d = depth[i]
        finite = np.isfinite(d)
        valid = finite & (d > 0)
        zero_ratio_per_frame.append(float((d == 0).mean()))
        valid_ratio_per_frame.append(float(valid.mean()))
        if valid.any():
            positive_depth_per_frame.append(float(d[valid].mean()))
        else:
            positive_depth_per_frame.append(0.0)

    zero_ratio_per_frame = np.array(zero_ratio_per_frame)
    valid_ratio_per_frame = np.array(valid_ratio_per_frame)
    positive_depth_per_frame = np.array(positive_depth_per_frame)

    print(
        f"zero_ratio:  min={zero_ratio_per_frame.min():.4f} "
        f"max={zero_ratio_per_frame.max():.4f} "
        f"mean={zero_ratio_per_frame.mean():.4f}"
    )
    print(
        f"valid_ratio: min={valid_ratio_per_frame.min():.4f} "
        f"max={valid_ratio_per_frame.max():.4f} "
        f"mean={valid_ratio_per_frame.mean():.4f}"
    )
    print(
        f"positive depth mean per frame: min={positive_depth_per_frame.min():.4f}m "
        f"max={positive_depth_per_frame.max():.4f}m "
        f"mean={positive_depth_per_frame.mean():.4f}m"
    )

    if valid_ratio_per_frame.mean() < 0.1:
        print("[WARN] valid depth ratio is very low. Check depth topic, unit, or camera view.")
    elif valid_ratio_per_frame.mean() < 0.5:
        print("[WARN] many depth pixels are invalid/zero.")
    else:
        print("[OK] depth has a reasonable amount of valid pixels.")


def check_rgb(name: str, rgb: np.ndarray):
    print(f"\n========== RGB quality: {name} ==========")
    print(arr_basic_stats(name, rgb))

    if rgb.ndim != 4 or rgb.shape[-1] != 3:
        print(f"[WARN] {name} expected shape [T, H, W, 3], got {rgb.shape}")
        return

    if rgb.shape[0] >= 2:
        diffs = []
        for i in range(1, min(rgb.shape[0], 50)):
            diff = np.mean(np.abs(rgb[i].astype(np.float32) - rgb[i - 1].astype(np.float32)))
            diffs.append(diff)
        diffs = np.array(diffs)
        print(
            f"adjacent frame abs diff sample: min={diffs.min():.4f} "
            f"max={diffs.max():.4f} mean={diffs.mean():.4f}"
        )
        if diffs.mean() < 0.1:
            print("[WARN] RGB frames barely change. This is okay if robot/camera is static, otherwise check subscription.")
        else:
            print("[OK] RGB frames have visible variation in sampled diffs.")


def check_action_motion(data: Dict[str, np.ndarray]):
    print("\n========== Action / motion checks ==========")

    if "action_delta.npy" in data:
        action = data["action_delta.npy"]
        print(arr_basic_stats("action_delta.npy", action))
        if action.ndim == 2 and action.shape[1] == 7:
            trans_norm = np.linalg.norm(action[:, :3], axis=1)
            rot_norm = np.linalg.norm(action[:, 3:6], axis=1)
            grip_abs = np.abs(action[:, 6])
            print(
                f"translation delta norm: min={trans_norm.min():.6f} "
                f"max={trans_norm.max():.6f} mean={trans_norm.mean():.6f}"
            )
            print(
                f"rotation delta norm:    min={rot_norm.min():.6f} "
                f"max={rot_norm.max():.6f} mean={rot_norm.mean():.6f}"
            )
            print(
                f"gripper delta abs:      min={grip_abs.min():.6f} "
                f"max={grip_abs.max():.6f} mean={grip_abs.mean():.6f}"
            )

            if np.allclose(action, 0):
                print("[BAD] action_delta is all zeros.")
            elif trans_norm.mean() < 1e-6 and rot_norm.mean() < 1e-6 and grip_abs.mean() < 1e-6:
                print("[WARN] action deltas are extremely small.")
            else:
                print("[OK] action_delta contains non-zero motion.")

    if "eef_pose.npy" in data:
        print(arr_basic_stats("eef_pose.npy", data["eef_pose.npy"]))


def save_visualizations(ep_dir: Path, data: Dict[str, np.ndarray], out_dir: Optional[Path] = None):
    import matplotlib.pyplot as plt

    if out_dir is None:
        out_dir = ep_dir / "check_vis"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"\n========== Saving visualizations to {out_dir} ==========")

    def save_rgb_grid(fname: str, title: str):
        if fname not in data:
            return
        arr = data[fname]
        if arr.ndim != 4 or arr.shape[-1] != 3 or arr.shape[0] == 0:
            return

        idxs = np.linspace(0, arr.shape[0] - 1, min(4, arr.shape[0])).astype(int)
        fig, axes = plt.subplots(1, len(idxs), figsize=(4 * len(idxs), 4))
        if len(idxs) == 1:
            axes = [axes]
        for ax, idx in zip(axes, idxs):
            img = arr[idx][..., ::-1]  # BGR -> RGB
            ax.imshow(img)
            ax.set_title(f"{title} t={idx}")
            ax.axis("off")
        fig.tight_layout()
        fig.savefig(out_dir / f"{fname.replace('.npy', '')}_preview.png", dpi=150)
        plt.close(fig)

    def save_depth_grid(fname: str, title: str):
        if fname not in data:
            return
        arr = data[fname]
        if arr.ndim != 3 or arr.shape[0] == 0:
            return

        idxs = np.linspace(0, arr.shape[0] - 1, min(4, arr.shape[0])).astype(int)
        fig, axes = plt.subplots(1, len(idxs), figsize=(4 * len(idxs), 4))
        if len(idxs) == 1:
            axes = [axes]
        for ax, idx in zip(axes, idxs):
            d = arr[idx]
            valid = d[d > 0]
            if valid.size > 0:
                vmax = np.percentile(valid, 95)
                vmin = np.percentile(valid, 5)
            else:
                vmin, vmax = 0.0, 1.0
            im = ax.imshow(d, cmap="viridis", vmin=vmin, vmax=vmax)
            ax.set_title(f"{title} t={idx}")
            ax.axis("off")
            fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        fig.tight_layout()
        fig.savefig(out_dir / f"{fname.replace('.npy', '')}_preview.png", dpi=150)
        plt.close(fig)

    save_rgb_grid("rgb_frames.npy", "RGB")
    save_rgb_grid("env_rgb_frames.npy", "Env RGB")
    save_depth_grid("depth_frames.npy", "Depth")
    save_depth_grid("env_depth_frames.npy", "Env Depth")

    if "action_delta.npy" in data:
        action = data["action_delta.npy"]
        if action.ndim == 2 and action.shape[1] == 7:
            fig = plt.figure(figsize=(12, 5))
            for i, label in enumerate(["dx", "dy", "dz", "droll", "dpitch", "dyaw", "dgripper"]):
                plt.plot(action[:, i], label=label)
            plt.title("action_delta")
            plt.xlabel("t")
            plt.legend()
            plt.tight_layout()
            fig.savefig(out_dir / "action_delta_plot.png", dpi=150)
            plt.close(fig)

    print("[OK] visualizations saved.")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("episode_dir", type=str, help="Path to episode_xxxxxx directory")
    parser.add_argument("--save-vis", action="store_true", help="Save preview images and action plot")
    parser.add_argument("--mmap", action="store_true", help="Use numpy mmap_mode='r' for lower memory usage")
    args = parser.parse_args()

    ep_dir = Path(args.episode_dir).expanduser().resolve()
    if not ep_dir.exists():
        raise FileNotFoundError(f"Episode directory does not exist: {ep_dir}")

    print(f"Checking episode: {ep_dir}")

    exists_ok, _ = check_exists(ep_dir)
    check_meta(ep_dir)

    print("\n========== Loading arrays ==========")
    data: Dict[str, np.ndarray] = {}

    for fname in REQUIRED_FILES + OPTIONAL_FILES:
        path = ep_dir / fname
        if not path.exists() or not fname.endswith(".npy"):
            continue
        try:
            arr = load_npy(path, mmap=args.mmap)
            data[fname] = arr
            print(arr_basic_stats(fname, arr))
        except Exception as e:
            print(f"[ERROR] failed to load {fname}: {e}")

    if not exists_ok:
        print("\n[WARN] Some required files are missing. Checks will continue with available files.")

    shape_ok = check_shapes(data)
    check_timestamps(data)

    if "rgb_frames.npy" in data:
        check_rgb("rgb_frames.npy", data["rgb_frames.npy"])
    if "env_rgb_frames.npy" in data:
        check_rgb("env_rgb_frames.npy", data["env_rgb_frames.npy"])

    if "depth_frames.npy" in data:
        check_depth("depth_frames.npy", data["depth_frames.npy"])
    if "env_depth_frames.npy" in data:
        check_depth("env_depth_frames.npy", data["env_depth_frames.npy"])

    if "pointcloud_frames.npy" in data:
        print("\n========== Point cloud checks ==========")
        pc = data["pointcloud_frames.npy"]
        print(arr_basic_stats("pointcloud_frames.npy", pc))
        if pc.ndim == 3 and pc.shape[-1] == 3:
            finite = np.isfinite(pc).all(axis=-1)
            nonzero = np.linalg.norm(pc, axis=-1) > 0
            valid = finite & nonzero
            print(f"point valid ratio: mean={valid.mean():.4f}")
            print("[OK] pointcloud shape looks like [T, N, 3].")
        else:
            print(f"[WARN] expected pointcloud shape [T, N, 3], got {pc.shape}")

    check_action_motion(data)

    if args.save_vis:
        save_visualizations(ep_dir, data)

    print("\n========== Final summary ==========")
    if shape_ok and exists_ok:
        print("[PASS] Basic dataset structure looks good.")
    else:
        print("[CHECK] Some issues were found above. Please inspect warnings/errors.")


if __name__ == "__main__":
    main()
